# Generated by Django 6.0.5 on 2026-05-21 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('package_type', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('speed', models.CharField(help_text='e.g., 10 Mbps, 20 Mbps', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Internet Package',
                'verbose_name_plural': 'Internet Packages',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_month', models.IntegerField(help_text='Month number (1-12) for the billing period')),
                ('billing_year', models.IntegerField(help_text='Year (YYYY) for the billing period')),
                ('invoice_date', models.DateField(help_text='Full date when invoice was generated')),
                ('billing_type', models.CharField(choices=[('monthly_bill', 'Monthly Internet Bill'), ('connection_fee', 'New Connection Fee')], max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('free', 'Free - No Charge'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid')], default='unpaid', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount that has been paid so far', max_digits=10)),
                ('payment_date', models.DateField(blank=True, help_text='Date when full payment was completed', null=True)),
                ('transaction_id', models.CharField(blank=True, help_text='Payment gateway transaction ID if applicable', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this invoice')),
                ('customer', models.ForeignKey(help_text='Customer this invoice belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customerprofile')),
                ('package', models.ForeignKey(blank=True, help_text='Internet package for this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.package')),
            ],
            options={
                'verbose_name': 'Customer Invoice',
                'verbose_name_plural': 'Customer Invoices',
                'ordering': ['-billing_year', '-billing_month', '-created_at'],
                'unique_together': {('customer', 'billing_month', 'billing_year', 'billing_type')},
            },
        ),
    ]
