# Generated by Django 6.0.5 on 2026-05-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
