# Generated by Django 6.0.5 on 2026-05-22 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_delete_invoice'),
        ('customers', '0004_customerprofile_customer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('free', 'Free - No Charge'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid')], default='unpaid', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_fees', to='customers.customerprofile')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.package')),
            ],
            options={
                'verbose_name': 'New Connection Fee',
                'verbose_name_plural': 'New Connection Fees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_month', models.IntegerField()),
                ('billing_year', models.IntegerField()),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(choices=[('free', 'Free - No Charge'), ('paid', 'Paid'), ('unpaid', 'Unpaid'), ('partial', 'Partially Paid')], default='unpaid', max_length=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_bills', to='customers.customerprofile')),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.package')),
            ],
            options={
                'verbose_name': 'Monthly Internet Bill',
                'verbose_name_plural': 'Monthly Internet Bills',
                'ordering': ['-billing_year', '-billing_month', '-created_at'],
                'unique_together': {('customer', 'billing_month', 'billing_year')},
            },
        ),
    ]
