# Generated by Django 6.0.5 on 2026-05-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_connectionfee_monthlybill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connectionfee',
            name='package',
        ),
        migrations.RemoveField(
            model_name='monthlybill',
            name='package',
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='package_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='monthlybill',
            name='package_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
