# Generated by Django 6.0.5 on 2026-06-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_connectionfee_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash Payment'), ('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank_transfer', 'Bank Transfer'), ('card', 'Credit/Debit Card'), ('adjustment', 'Manual Adjustment'), ('other', 'Other')], default='cash', max_length=20),
        ),
    ]
