export const API = {
  auth: {
    login: "/auth/login/",
    logout: "/auth/logout/",
    user: "/auth/user/",
  },
  customers: "/customers/",
  customerOnlineStatus: "/customers/online_status/",
  customerDetail: (id: string | number) => `/customers/${id}/`,
  customerUpdateBilling: (id: string | number) => `/customers/${id}/update_billing/`,
  customerLiveStats: (id: string | number) => `/customers/${id}/live_stats/`,
  customerStatus: (id: string | number) => `/customers/${id}/update_status/`,
  customerConnection: (id: string | number) => `/customers/${id}/update_connection/`,
  zones: "/zones/",
  packages: "/billing/packages/",
  routers: "/mikrotik/routers/",
  tickets: "/tickets/",
  ticketDetail: (id: number | string) => `/tickets/${id}/`,
  ticketReply: (id: number | string) => `/tickets/${id}/reply/`,
  scheduler: "/scheduler/",
  billing: {
    monthlyBills: "/billing/billing/monthly_bills/",
    transactions: "/billing/billing/transactions/",
    connectionFees: "/billing/billing/connection_fees/",
    generateMonthlyBills: "/billing/billing/generate_monthly_bills/",
    addTransaction: "/billing/billing/add_transaction/",
    generateConnectionFee: "/billing/billing/generate_connection_fee/",
  },
  routerProfiles: (id: number | string) => `/mikrotik/routers/${id}/get_profiles/`,
  reports: {
    dashboard: "/reports/dashboard/",
  },
  bandwidth: {
    live: "/bandwidth/live/",
    sync: "/bandwidth/sync/",
    summary: "/bandwidth/summary/",
    logs: "/bandwidth/logs/",
    topUsers: "/bandwidth/top-users/",
    routerSummaries: "/bandwidth/router-summaries/",
    export: "/bandwidth/export/",
  },
  olt: {
    devices: "/olt/devices/",
    onus: "/olt/onus/",
    testConnection: (id: number | string) => `/olt/devices/${id}/test_connection/`,
    syncOnus: (id: number | string) => `/olt/devices/${id}/sync_onus/`,
  },
  sms: {
    gateways: "/sms/gateways/",
    templates: "/sms/templates/",
    logs: "/sms/logs/",
    providers: "/sms/sms/providers/",
    send: "/sms/sms/send/",
    test: (id: number | string) => `/sms/gateways/${id}/test/`,
    setDefault: (id: number | string) => `/sms/gateways/${id}/set_default/`,
  },
} as const;
