# Generated by Django 6.0.5 on 2026-06-03 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0006_ticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='OltDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('host', models.CharField(help_text='OLT IP address or hostname', max_length=255)),
                ('vendor', models.CharField(choices=[('huawei', 'Huawei'), ('zte', 'ZTE'), ('vsol', 'VSOL'), ('cdata', 'C-Data'), ('bdcom', 'BDCOM'), ('generic', 'Generic / Other')], default='generic', max_length=20)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('pon_type', models.CharField(choices=[('gpon', 'GPON'), ('epon', 'EPON')], default='gpon', max_length=10)),
                ('snmp_community', models.CharField(default='public', max_length=100)),
                ('snmp_version', models.CharField(choices=[('v1', 'v1'), ('v2c', 'v2c')], default='v2c', max_length=4)),
                ('snmp_port', models.IntegerField(default=161)),
                ('ssh_username', models.CharField(blank=True, default='', max_length=100)),
                ('ssh_password', models.CharField(blank=True, default='', max_length=255)),
                ('ssh_port', models.IntegerField(default=22)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=10)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Onu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onu_index', models.CharField(blank=True, default='', help_text='SNMP index / internal ONU id', max_length=50)),
                ('serial_number', models.CharField(blank=True, default='', max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('pon_port', models.CharField(blank=True, default='', help_text='e.g. 0/1/1', max_length=40)),
                ('onu_model', models.CharField(blank=True, default='', max_length=80)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('los', 'Loss of signal'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('rx_power', models.DecimalField(blank=True, decimal_places=2, help_text='ONU Rx power (dBm)', max_digits=6, null=True)),
                ('tx_power', models.DecimalField(blank=True, decimal_places=2, help_text='ONU Tx power (dBm)', max_digits=6, null=True)),
                ('olt_rx_power', models.DecimalField(blank=True, decimal_places=2, help_text='Rx power at OLT (dBm)', max_digits=6, null=True)),
                ('distance', models.IntegerField(blank=True, help_text='Distance in meters', null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onus', to='customers.customerprofile')),
                ('olt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onus', to='olt.oltdevice')),
            ],
            options={
                'ordering': ['olt', 'pon_port', 'onu_index'],
                'unique_together': {('olt', 'onu_index')},
            },
        ),
    ]
