# Generated by Django 6.0.5 on 2026-06-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oltdevice',
            options={'ordering': ['name', 'host']},
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='model',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='snmp_version',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='ssh_port',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='ssh_username',
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='olt_type',
            field=models.CharField(choices=[('VSOL_EPON', 'VSOL EPON'), ('VSOL_GPON', 'VSOL GPON'), ('CDATA_EPON', 'C-Data EPON'), ('CDATA_GPON', 'C-Data GPON'), ('PHOTON_EPON', 'Photon EPON'), ('ZTE_EPON', 'ZTE EPON'), ('ZTE_GPON', 'ZTE GPON'), ('HUAWEI_GPON', 'Huawei GPON'), ('BDCOM_EPON', 'BDCOM EPON'), ('BDCOM_GPON', 'BDCOM GPON'), ('GENERIC_EPON', 'Generic EPON'), ('GENERIC_GPON', 'Generic GPON')], default='GENERIC_EPON', max_length=20),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='web_ip',
            field=models.CharField(blank=True, default='', help_text='Web UI address, e.g. 10.0.0.2:8080', max_length=255),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='web_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='web_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='oltdevice',
            name='host',
            field=models.CharField(help_text='OLT IP address', max_length=255),
        ),
        migrations.AlterField(
            model_name='oltdevice',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='oltdevice',
            name='pon_type',
            field=models.CharField(default='epon', max_length=10),
        ),
        migrations.AlterField(
            model_name='oltdevice',
            name='vendor',
            field=models.CharField(default='generic', max_length=20),
        ),
    ]
