# Generated by Django 6.0.5 on 2026-06-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0002_alter_oltdevice_options_remove_oltdevice_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oltdevice',
            name='web_ip',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='web_password',
        ),
        migrations.RemoveField(
            model_name='oltdevice',
            name='web_username',
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='protocol',
            field=models.CharField(choices=[('http', 'HTTP'), ('https', 'HTTPS')], default='http', max_length=5),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='telnet_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='telnet_port',
            field=models.IntegerField(default=23),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='telnet_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='timeout',
            field=models.IntegerField(default=10, help_text='Connection timeout in seconds'),
        ),
        migrations.AddField(
            model_name='oltdevice',
            name='web_port',
            field=models.IntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='oltdevice',
            name='olt_type',
            field=models.CharField(choices=[('VSOL_EPON', 'VSOL EPON'), ('VSOL_GPON', 'VSOL GPON'), ('CDATA_EPON', 'C-Data EPON'), ('CDATA_GPON', 'C-Data GPON'), ('PHOTON_EPON', 'Photon EPON'), ('ZTE_EPON', 'ZTE EPON'), ('ZTE_GPON', 'ZTE GPON'), ('HUAWEI_GPON', 'Huawei GPON'), ('BDCOM_EPON', 'BDCOM EPON'), ('BDCOM_GPON', 'BDCOM GPON'), ('GENERIC_EPON', 'Generic EPON'), ('GENERIC_GPON', 'Generic GPON')], default='GENERIC_EPON', help_text='OLT brand & technology type', max_length=20),
        ),
    ]
