# Generated by Django 6.0.5 on 2026-09-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olt', '0003_remove_oltdevice_web_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oltdevice',
            name='olt_type',
            field=models.CharField(choices=[('VSOL_EPON', 'VSOL EPON'), ('VSOL_EPON_TYPE_2', 'VSOL EPON (Type 2)'), ('VSOL_GPON', 'VSOL GPON'), ('CDATA_EPON', 'C-Data EPON'), ('CDATA_GPON', 'C-Data GPON'), ('PHOTON_EPON', 'Photon EPON'), ('ZTE_EPON', 'ZTE EPON'), ('ZTE_GPON', 'ZTE GPON'), ('HUAWEI_GPON', 'Huawei GPON'), ('BDCOM_EPON', 'BDCOM EPON'), ('BDCOM_GPON', 'BDCOM GPON'), ('CORELINK_EPON', 'CoreLink EPON'), ('AVEIS_EPON', 'AVEIS EPON'), ('GENERIC_EPON', 'Generic EPON'), ('GENERIC_GPON', 'Generic GPON')], default='GENERIC_EPON', help_text='OLT brand & technology type', max_length=20),
        ),
    ]
