# Generated by Django 6.0.5 on 2026-05-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerprofile_package_delete_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active - Connected'), ('disconnected', 'Disconnected')], default='active', max_length=15),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='extended_billing_days',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='RouterInfo',
        ),
    ]
