# Generated by Django 6.0.5 on 2026-05-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customerprofile_billing_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='customer_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
