# Generated by Django 6.0.5 on 2026-05-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_customerprofile_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
