# Generated by Django 6.0.5 on 2026-06-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_ticketreply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='customer_status',
            field=models.CharField(choices=[('active', 'Active - Connected'), ('disconnected', 'Disconnected'), ('free', 'Free / Complimentary'), ('left', 'Left / Churned')], default='active', max_length=15),
        ),
    ]
