# Generated by Django 6.0.5 on 2026-06-03 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0007_alter_customerprofile_customer_status'),
        ('mikrotik', '0002_routerinfo_profile_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BandwidthSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pppoe_id', models.CharField(db_index=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=255)),
                ('upload_bytes', models.BigIntegerField(default=0, help_text='Bytes received from the customer (RX)')),
                ('download_bytes', models.BigIntegerField(default=0, help_text='Bytes sent to the customer (TX)')),
                ('uptime', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandwidth_samples', to='customers.customerprofile')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bandwidth_samples', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'Bandwidth Sample',
                'verbose_name_plural': 'Bandwidth Samples',
                'ordering': ['-created_at'],
            },
        ),
    ]
