# Generated by Django 6.0.5 on 2026-05-21 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customerprofile_billing_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MikrotikRouter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Router name for identification', max_length=100)),
                ('host', models.CharField(help_text='Router IP address or hostname', max_length=255)),
                ('port', models.IntegerField(default=8728, help_text='API port (default: 8728)')),
                ('username', models.CharField(help_text='Router API username', max_length=100)),
                ('password', models.CharField(help_text='Router API password (stored as plaintext)', max_length=255)),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL for connection')),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Connection Error')], default='disconnected', max_length=20)),
                ('last_checked', models.DateTimeField(blank=True, help_text='Last connection check time', null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'MikroTik Router',
                'verbose_name_plural': 'MikroTik Routers',
            },
        ),
        migrations.CreateModel(
            name='RouterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pppoe_name', models.CharField(max_length=255)),
                ('pppoe_pass', models.CharField(max_length=255)),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='router_info', to='customers.customerprofile')),
                ('router', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_routers', to='mikrotik.mikrotikrouter')),
            ],
            options={
                'verbose_name': 'Customer Router Info',
                'verbose_name_plural': 'Customer Router Infos',
            },
        ),
    ]
