# Generated by Django 6.0.5 on 2026-06-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mikrotik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='routerinfo',
            name='profile_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
